### ISSUE TITLE
[Feature request]  CMD commsnd to open excel and other tools

### ISSUE THREAD

**Issue by Naren456** [Bashamega/Windows-cmd-extensions#15]
I've looked at the code and I'd like to add a feature to your current project for opening other applications using cmd commands, I'd like to open applications like excel, powerpoint etc. on this basis

**Comment by Bashamega** [comment]
Hello:)
For this you can actually use the [open command](https://bashamega.github.io/Windows-cmd-extensions/web/?name=open) to do that.
