### ISSUE TITLE
Unable to run the Executable

### ISSUE THREAD

**Issue by Varun270** [Bashamega/Windows-cmd-extensions#20]
I have encountered this problem today while trying to execute the .exe file of our project. It is throwing a keyerror under unhandled exception.

<img width="315" alt="uE" src="https://github.com/user-attachments/assets/4bab24c8-3e65-4130-9ecb-b14e75e58b0b">

Steps to Reproduce - 
1] Download the exe
2] Run as administrator
3] You will see the erroneous dialogue box

Possible Reasons - 

After doing some digging, I guess this PR #14  could be the reason behind the issue. Since before merging it the code was working fine. Also the problem seems to arise within the JSON file which has been updated recently.

**Comment by Bashamega** [comment]
It is working now. I hade to fix something in the db 
NOTE: you don't need to download it again
![image](https://github.com/user-attachments/assets/24f8db31-5c44-459d-a0cf-6bdaa53c8a48)
